### PR TITLE
Reformat config files for reordering

### PR DESCRIPTION
**Pull request by laurafeier**
Result of configlet fmt.
 See exercism/meta#95 

 Created at ROSSConf. /cc @kytrinyx

### CODE REVIEW

**Comment by NobbZ** [comment]
Please accept the semantic difference between the empty list and a null value, also both files should end in a newline to make them POSIX compliant textiles.

**Comment by kytrinyx** [comment]
I'm opening an issue in the configlet repo about this—the author if this pull request is not the same as the one who implemented the changes to `fmt`.

**Comment by kytrinyx** [comment]
Ah, these have already been opened:

https://github.com/exercism/configlet/issues/129
https://github.com/exercism/configlet/issues/128

**Comment by NobbZ** [comment]
This PR was superseeded by #246.

**Pull request closed without merging**
