### PR TITLE
[fetch-configlet] update script to match latest version from upstream

### PR DESCRIPTION
**Pull request by NobbZ**
Review requested by @ErikSchierboom or @iHiD as @exercism/erlang is effectively just me, and I can not review myself.

### CODE REVIEW

**Review by iHiD — APPROVED** [review]
Approving without actually reviewing anything, so that you can move forward.

**Comment by NobbZ** [comment]
Just realising that I can not do a merge commit, I do not mind squashing this commit, as its only a single commit anyway, though I'd prefer to have a merge commit for future merges. Can you please re-enable "merge commits" and "rebase and merge"?

**Comment by iHiD** [comment]
Done.

**Review by ErikSchierboom — COMMENTED** [review]
LGTM

**Pull request merged**
