### PR TITLE
[poker] implement exercise

### PR DESCRIPTION
**Pull request by chilikk**
Refs https://github.com/exercism/erlang/issues/196

### CODE REVIEW

**Comment by juhlig** [comment]
In reference to #278, please remove the test version related functions from the test, example solution, and module stub.

Instead, at the top of the test file, note the version of the canonical data it implements (`1.1.0` at the time of this writing) and a link to the raw view of the canonical data on github, like this:
```erlang
%% based on canonical data version 1.1.0
%% https://raw.githubusercontent.com/exercism/problem-specifications/master/exercises/poker/canonical-data.json
```

Otherwise, I'd say it's good :)

**Comment by chilikk** [comment]
Thanks, done!

**Comment by juhlig** [comment]
Thanks :)

Just one more thing, I might have overlooked that in your first commit (sorry): As a convention, the stub functions in the module skeleton should return `undefined` (your returns `[]`. If you could change that, it's good to go :)

**Comment by chilikk** [comment]
Oh, ok, sure. I guess I was just trying to follow my own spec for the function.

**Comment by juhlig** [comment]
Merged, thanks :)

**Pull request merged**
