### PR TITLE
Add back deleted, deprecated exercises

### PR DESCRIPTION
**Pull request by kytrinyx**
When migrating the data from v1 to v2, we will lose all the solutions submitted to
deprecated exercises, unless they exist in the track configuration.

This adds the deprecated binary and trinary exercises back, leaving them
 deprecated so that they don't actively show up as part of the track.

We can delete them from the track again after we launch v2, if we want to.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@NobbZ I'm not quite sure what I've done wrong with this one. It looks like the binary exercise is failing the Journey test. Would you mind helping me out?

**Comment by NobbZ** [comment]
I applied some fixes and updated them to a more modern approach of detecting the environment. I'll go to bed soon, so feel free to merge if tests pass. I'll have a look tomorrow if they still fail.

**Comment by kytrinyx** [comment]
Thanks @NobbZ. They're still failing; would you take another look?

**Comment by NobbZ** [comment]
Yeah, I have already realized it this morning, but end of year preparations are much more time consuming than thaught… And since there will be  depreps tomorrow, I probably won't be able to look into this again before January 2nd…

**Comment by kytrinyx** [comment]
@NobbZ That is perfect thank you!

**Comment by NobbZ** [comment]
Okay, I did find the problem, but can't fix it right now.

I'll need to touch the exercism-helper-library and the journey-script.

The problem is basically that I create module names from exercise names and `binary` is mapped plain to `binary`. This name though is already taken by erlangs stdlib.

So I need to override this modulename in both aforementioned tools.

**Comment by kytrinyx** [comment]
That makes sense, thank you @NobbZ.

**Comment by NobbZ** [comment]
Sorry, I was not able to do anything in this regard… Last weak I accidentally uninstalled `gcc` on my laptop. In the process of fixing this (on a source only linux distribution) I made it worse and therefore I started re-installing linux this morning. ETA until all packages are compiled and installed is about Tuesday evening, then I need to transfer the data backup… In the future I'll probably do a full backup ;)

I do hope I do find some time during office hours and fix this before my laptop is ready ;)

**Comment by kytrinyx** [comment]
Oh, no, @NobbZ, that sounds painful (and thanks for the heads up).

**Comment by NobbZ** [comment]
Just a small lifesign from me.

I have not forgotten this, but family and dayjob are eating most of my available time.

I do hope to be able to fix this during the next 4 weeks…

**Comment by kytrinyx** [comment]
Thanks for the ping @NobbZ. Best of luck with life, family and work in the meantime (I completely understand!)

**Comment by NobbZ** [comment]
As we never have been able to resolve this issue and therefore not merged this branch before migrations, the solutions probably are lost now anyway and can't get recovered.

Should we delete the branch to clean up branches list?

**Pull request closed without merging**
