### PR TITLE
Implementation of the resistor-color exercise

### PR DESCRIPTION
**Pull request by juhlig**
Not sure about the difficulty rating. By intuition, it is just a `1`, but all the other exercises at that difficulty are `core`.

Test generator: https://github.com/exercism/erlang-tests-generator/pull/26

### CODE REVIEW

**Comment by juhlig** [comment]
Since there are more resistor exercises (`resistor-color-duo` and `resistor-color-trio`), maybe this should be made a core exercise with the others behind it?

**Comment by sshine** [comment]
> maybe this should be made a core exercise with the others behind it

It was created with this intent, so if it serves a didactical purpose on the Erlang track, certainly.

It didn't exist on the Haskell track in spite of -duo and -trio having been implemented.

Someone enquired on Slack recently about this, which drove me to mark it as foregone for reasons of it being too simple: exercism/haskell#888. But perhaps in the context of v3 "concept exercises" it isn't too simple, and perhaps in Erlang it's not a matter of derived one-liners.

**Comment by NobbZ** [comment]
With v3 coming soon, I'm not really in love with the idea to juggle exercises around or implement much more exercises than we've actually already.

Instead I'd prefer focussing on v3. With its release in about 6 months, all current structure will be lost and the current available exercises will be moved into a flat practicing mode, which is more like the current side exercises.

**Comment by NobbZ** [comment]
Closing this PR due to v2 beeing frozen anyway

**Pull request closed without merging**
